/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 */

import type { IKibanaResponse, Logger } from '@kbn/core/server';
import { transformError } from '@kbn/securitysolution-es-utils';
import type { SecuritySolutionPluginRouter } from '../../../types';
import { buildSiemResponse } from '../../../lib/detection_engine/routes/utils';
import type { GetAgentPolicySummaryResponse } from '../../../../common/api/endpoint/policy/policy.gen';
import { handleGetAgentPolicySummaryRequest } from './handle_get_agent_policy_summary_request.gen';

export const GetAgentPolicySummaryRoute = (
  router: SecuritySolutionPluginRouter,
  logger: Logger
) => {
  router.versioned
    .get({
      access: 'public',
      path: '/api/endpoint/policy/summaries',
      options: {
        tags: ['access:securitySolution'],
      },
    })
    .addVersion(
      {
        version: '2023-10-31',
        validate: false,
      },
      async (
        context,
        request,
        response
      ): Promise<IKibanaResponse<GetAgentPolicySummaryResponse>> => {
        const siemResponse = buildSiemResponse(response);

        try {
          const result = await handleGetAgentPolicySummaryRequest(context, request, logger);

          return response.ok({
            body: result,
          });
        } catch (err) {
          const error = transformError(err);
          return siemResponse.error({
            body: error.message,
            statusCode: error.statusCode,
          });
        }
      }
    );
};
