/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 */

import type { IKibanaResponse, Logger } from '@kbn/core/server';
import { transformError } from '@kbn/securitysolution-es-utils';
import type { SecuritySolutionPluginRouter } from '../../../../../types';
import { buildSiemResponse } from '../../../routes/utils';
import type { GetPrebuiltRulesAndTimelinesStatusResponse } from '../../../../../../common/api/detection_engine/prebuilt_rules/get_prebuilt_rules_and_timelines_status/get_prebuilt_rules_and_timelines_status_route.gen';
import { handleGetPrebuiltRulesAndTimelinesStatusRequest } from './handle_get_prebuilt_rules_and_timelines_status_request.gen';

export const GetPrebuiltRulesAndTimelinesStatusRoute = (
  router: SecuritySolutionPluginRouter,
  logger: Logger
) => {
  router.versioned
    .get({
      access: 'public',
      path: '/api/detection_engine/rules/prepackaged/_status',
      options: {
        tags: ['access:securitySolution'],
      },
    })
    .addVersion(
      {
        version: '2023-10-31',
        validate: false,
      },
      async (
        context,
        request,
        response
      ): Promise<IKibanaResponse<GetPrebuiltRulesAndTimelinesStatusResponse>> => {
        const siemResponse = buildSiemResponse(response);

        try {
          const result = await handleGetPrebuiltRulesAndTimelinesStatusRequest(
            context,
            request,
            logger
          );

          return response.ok({
            body: result,
          });
        } catch (err) {
          const error = transformError(err);
          return siemResponse.error({
            body: error.message,
            statusCode: error.statusCode,
          });
        }
      }
    );
};
