/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 */

import type { Logger, RequestHandlerContext, KibanaRequest } from '@kbn/core/server';
import type { InstallPrebuiltRulesAndTimelinesResponse } from '../../../../../../common/api/detection_engine/prebuilt_rules/install_prebuilt_rules_and_timelines/install_prebuilt_rules_and_timelines_route.gen';

export async function handleInstallPrebuiltRulesAndTimelinesRequest(
  context: RequestHandlerContext,
  request: KibanaRequest,
  logger: Logger
): Promise<InstallPrebuiltRulesAndTimelinesResponse> {
  // YOUR BUSINESS LOGIC GOES HERE
}
